### ISSUE TITLE
hline for the last row repeated at the end of every page in longtblr

### ISSUE THREAD

**Issue by goriy** [lvjr/tabularray#238] opened 2022-04-23 23:19 UTC
When specific hline parameters are set for the last row of long table, they repeated not only at the last row, but at the last row on every page. It doesn't matter what syntax is used: `hline={}` or `\SetHline{}`, both cases lead to the same result.
Although, similar vline parameters work as expected (apply only to the last row in table).

```latex
\documentclass[12pt]{article}
\usepackage{tabularray}
\usepackage{lipsum}
\usepackage[a6paper,margin=15mm]{geometry}

\begin{document}
\lipsum[2]

\begin{longtblr}
{
hline{Z} = {3-Z}{3pt}, %% hline creates duplicated lines
vline{2} = {Z}{3pt}   %% although, vline works fine
}
Name   & Value & Description \\ \hline
name1  & 10  & None \\
name2  & 10  & None \\
name3  & 10  & None \\
name4  & 10  & None \\
name5  & 10  & None \\
%\SetHline{3-3}{3pt} %% this syntax leads to the same result
\end{longtblr}

\end{document}
```

![image](https://user-images.githubusercontent.com/14969214/164948870-0d4b71df-2492-43ff-a820-7d7d0f126afc.png)

**Comment by lvjr** [comment] 2022-04-24 07:11
It is a duplicate of #130.

**Closed by lvjr** 2022-04-24 07:11 UTC
Labels: duplicate
