### ISSUE TITLE
Tabularray sometimes bugs within amsmath gather

### ISSUE THREAD

**Issue by dbontemps** [lvjr/tabularray#211] opened 2022-03-11 12:51 UTC
On my new texlive distribution (vanilla texlive 2021 over Ubuntu 20.04), tabularray sometimes doesn't work within gather (from amsmath). For example

\begin{gather*}
 \begin{tblr}{l}
  a \\ b
 \end{tblr}
\end{gather*}

does work, while

\begin{gather*}
 \begin{tblr}{ll}
  a & b
 \end{tblr}
\end{gather*}

does not. A fix was proposed on https://tex.stackexchange.com/questions/636674/tabularray-sometimes-bugs-within-amsmath-gather

**Comment by lvjr** [comment] 2022-03-11 13:20
It is a duplicate of issue #143.

**Closed by lvjr** 2022-03-11 13:20 UTC
