### ISSUE TITLE
Changing font series/shape in multiline cells results in wrong column width

### ISSUE THREAD

**Issue by Sonja-K** [lvjr/tabularray#17] opened 2021-06-05 15:38 UTC
The documentation mentions creating multiline cells using the following syntax: `{text  \\ in \\ multiple \\ lines}`. 

Doing so works perfectly fine, but how can I change the font series/shape to bold, italics or small caps in such a multiline cell? The following MWE, that was tested using version 2021J and 2021K shows some attempts and their outcomes:

```
\documentclass{article}
\usepackage{tabularray}

\begin{document}

Use of \verb|\\| inside of \verb|\textit| leads to overly wide column:

\begin{tblr}{|l|l|}
text & {\textit{text  \\ in \\ multiple \\ lines}} \\ 
\end{tblr}

Without \verb|\textit| the column width is calculated correctly:

\begin{tblr}{|l|l|}
text & {text  \\ in \\ multiple \\ lines} \\ 
\end{tblr}

Using \verb|\itshape| instead of \verb|\textit| seems to solve the issue:

\begin{tblr}{|l|l|}
text & {\itshape text \\ in \\ multiple \\ lines} \\ 
\end{tblr}

Using \verb|\bfseries| or \verb|\scshape| results in overfull box warnings and wrong widths:

\begin{tblr}{|l|l|}
text & {\scshape text \\ in \\ multiple \\ lines} \\ 
\end{tblr}
\quad
\begin{tblr}{|l|l|}
text & {\bfseries text \\ in \\ multiple \\ lines} \\ 
\end{tblr}

Using \verb|\textbf|\ on each line individually does result in the expected output, but is somewhat inconvenient:

\begin{tblr}{|l|l|}
text & {\textbf{text} \\ \textbf{in} \\ \textbf{multiple} \\ \textbf{lines}} \\ 
\end{tblr}

\end{document}
```

![tabularray-colwidths](https://user-images.githubusercontent.com/30843621/120896916-f9152680-c623-11eb-968c-99736bde5d5e.png)

**Comment by lvjr** [comment] 2021-06-06 00:21
By design, if you need to set font for some lines in the cell, you must set it one by one. Therefore only the following two ways are correct:
````latex
{{\bfseries text} \\ in \\ multiple \\ {\bfseries lines}}
{\textbf{text} \\ in \\ multiple \\ \textbf{lines}}
````
And if you need to set font for all lines in the cell, you should use `font` option (see #2). There are some problems with `font` option, and I need to fix it.

**Comment by Sonja-K** [comment] 2021-06-06 09:29
Thanks for your fast reply. I unfortunately entirely overlooked the `font` option in the manual.

Out of curiosity: are the following differences in the expected (right)  and actual output with the `font` option (left)  what you were referring to when stating there was a problem with the font option? (Tested using version 2021K)

![tabularray-font](https://user-images.githubusercontent.com/30843621/120919461-f9600100-c6b9-11eb-9a05-b5db4237fe0c.png)

```
\documentclass{article}
\usepackage{tabularray}

\begin{document}

\begin{tblr}[t]{colspec={|l|l|}, cell{1}{2} = {font=\bfseries}} 
text & {text  \\ in \\ multiple \\ lines} \\ 
\end{tblr}
\quad
\begin{tblr}[t]{colspec={|l|l|}} 
text & {\textbf{text}  \\ \textbf{in} \\ \textbf{multiple} \\ \textbf{lines}} \\ 
\end{tblr}
\bigskip

\begin{tblr}[t]{colspec={|l|l|}, cell{1}{2} = {font=\tiny}} 
text & {text  \\ in \\ multiple \\ lines} \\ 
\end{tblr}
\quad
\begin{tblr}[t]{colspec={|l|l|}} 
text & {\tiny text  \\ \tiny in \\ \tiny multiple \\ \tiny lines} \\ 
\end{tblr}

\end{document}
```

**Comment by lvjr** [comment] 2021-06-06 09:43
Yes, this is the bug that I need to fix. The left side should be the same as the right side.

But the package doesn't support the following:
````latex
text & {\tiny text  \\ \tiny in \\ \tiny multiple \\ \tiny lines} \\ 
````
Instead you need to write the following:
````latex
text & {{\tiny text}  \\ {\tiny in} \\ {\tiny multiple} \\ {\tiny lines}} \\ 
````

**Comment by Sonja-K** [comment] 2021-06-06 10:59
That's interesting. According to my tests, I get a different output, if I enclose the text and the `\tiny` in an additional set of `{}`.

Let's compare the three versions in the below MWE:

- left= with the font option: Line spacing as expected, column width too wide due to bug
- middle = with `\tiny text \\`: line spacing and column width as expected (compare "alternative approaches" below)
- right = with `{\tiny text}\\`: column width as expected, too large line spacing


![tabularray-font2](https://user-images.githubusercontent.com/30843621/120921785-aa1fcd80-c6c5-11eb-8f6f-6c61524c3c9d.png)

As stated above, the expected output for me is the one in the middle of the first row. Using `text & {{\tiny text}  \\ {\tiny in} \\ {\tiny multiple} \\ {\tiny lines}} \\` as you recommended in your previous comment, I however get a different output with too large line spacing, especially compared to the alternative approaches in the second row of tables. Do I expect the wrong output or is this yet another bug?

```
\documentclass{article}
\usepackage{tabularray}

\usepackage{array}
\usepackage{makecell}

\begin{document}
\begin{tblr}[t]{colspec={|l|l|}, cell{1}{2} = {font=\tiny}} 
text & {text  \\ in \\ multiple \\ lines} \\ 
\end{tblr}
\quad
\begin{tblr}[t]{colspec={|l|l|}} 
text & {\tiny text  \\ \tiny in \\ \tiny multiple \\ \tiny lines} \\ 
\end{tblr}
\quad
\begin{tblr}[t]{colspec={|l|l|}} 
text & {{\tiny text}  \\ {\tiny in} \\ {\tiny multiple} \\ {\tiny lines}} \\ 
\end{tblr}
\bigskip

Using alternative, tabular based approaches:

\begin{tabular}[t]{|l|>{\tiny}p{1cm}|}
text & text in multiple lines 
\end{tabular}
\quad
\begin{tabular}[t]{|l|l|}
text & \tiny\makecell[tl]{text  \\ in \\ multiple \\ lines}
\end{tabular}
\end{document}
```

**Comment by lvjr** [comment] 2021-06-07 01:10
Yes, you are right. It seems when using font size commands, the result is not the same as using `font` option. Using `\makecell` also get different results.
````latex
\begin{tabular}[t]{|l|l|}
text & \makecell[l]{{\tiny text}  \\ {\tiny in} \\ {\tiny multiple} \\ {\tiny lines}}
\end{tabular}
````
But it's not the job of this package to check the content of cells, therefore you need to adjust vertical space by yourself.

**Comment by lvjr** [comment] 2021-06-09 12:08
This bug should be fixed now:
````latex
\begin{tblr}{
  colspec = {|l|l|l|}, cell{1}{2} = {font=\small}, cell{1}{3} = {font=\bfseries},
}
  {text  \\ in \\ multiple \\ lines}
& {text  \\ in \\ multiple \\ lines}
& {text  \\ in \\ multiple \\ lines}
\end{tblr}
````
![image](https://user-images.githubusercontent.com/4239949/121351468-64316680-c95e-11eb-9a10-64fe12b50048.png)

**Closed by lvjr** 2021-06-09 12:08 UTC
Labels: bug

**Comment by Sonja-K** [comment] 2021-06-12 08:14
Great. Thanks a lot for this fast update.
