### ISSUE TITLE
+cases does not work in align

### ISSUE THREAD

**Issue by Firestar-Reimu** [lvjr/tabularray#314] opened 2022-10-04 09:52 UTC
## This is good

```
\documentclass{article}
\usepackage{amsmath}

\begin{document}
    \begin{align}
        a_n
        &= (-1)^n \\
        &=
        \begin{cases}
            1, & n\ \text{is even} \\
            -1, & n\ \text{is odd}
        \end{cases}
    \end{align}
\end{document}
```

## This is bad

```
\documentclass{article}
\usepackage{amsmath}
\usepackage{tabularray}
\UseTblrLibrary{amsmath}

\begin{document}
    \begin{align}
        a_n
        &= (-1)^n \\
        &=
        \begin{+cases}
            1, & n\ \text{is even} \\
            -1, & n\ \text{is odd}
        \end{+cases}
    \end{align}
\end{document}
```

```
Extra }, or forgotten $.
<recently read> }
\begin{align} on input line 7 ended by \end{+cases}.
Misplaced alignment tab character &.
\@tempa ->\endgroup &&
...
```

**Comment by lvjr** [comment] 2022-10-05 13:22
Actually, the latest source code of `tabularray` doesn't use `environ` package.

**Comment by antshar** [comment] 2024-04-27 17:44
Any updates on this?

**Comment by muzimuzhi** [comment] 2024-04-28 04:54
Duplicate of #143.

**Closed by muzimuzhi** 2024-04-28 04:54 UTC
