### ISSUE TITLE
The text inside the merged cellls does not span correctly to the next page with longtblr?

### ISSUE THREAD

**Issue by nihilboy** [lvjr/tabularray#384] opened 2023-03-17 16:12 UTC
Here is the code i used:

```
\documentclass{article}
\usepackage[table, svgnames, dvipsnames]{xcolor}
\usepackage{tabularray}

\usepackage{lipsum}


\UseTblrLibrary{varwidth}


\ExplSyntaxOn
\NewChildSelector{eacheleven}
  {
    \int_step_inline:nnnn {2}{11}{\l_tblr_childs_total_tl}
      { \clist_put_right:Nn \l_tblr_childs_clist {##1} }
  }
\ExplSyntaxOff

\begin{document}
\scriptsize
\newcommand\myrow[9]{#1 & TEXT1 & #2 & #3 \\
                      &  TEXT2 & #4 \\
                      & TEXT3 & #5 \\
                      & TEXT4 TEXT & #6 \\
                      & TEXT5 & #7 \\
                       & TEXT6 & #8 \\
                       & TEXT7 TEXT. & #9 \\ 
                       }

\newcommand\myrowcont[4]{ & TEXT8 & #1 \\
                      & TEXT TEXT9. & #2 \\ 
                      & TEXT TEXT10 . & #3 \\
                       & TEXT TEXT11 & #4 \\
                       }

\scriptsize
\begin{longtblr}[expand=\expanded,
    caption = {CaPTION},
    label = {TABLE},
    ]{
        colspec = {|X[0.35,j, h] |X[0.47,j,l] |X[1.5,j,c]|X[0.7,j,h]},
        rowhead = 1, 
        hlines, vlines,
        cell{even}{2-3} = {WhiteSmoke},
        cell{odd}{2-3} = {white},
        row{1} = {FloralWhite},
        column{1,2} = {font=\bfseries},
        cell{1}{2} = {c=2}{c},
        cell{1}{4} = {font=\bfseries},
        cell{eacheleven}{1,4} = {r=11}{c},
        measure = vbox
    } 

ONE & TWO & & THREE\\

\expanded{\myrow{text}{text}{text}{text}{text}{text)}{text}{text }{text}}
\expanded{\myrowcont{text}{text}{text}{text }}

\expanded{\myrow{text}{text}{text}{text}{text}{text)}{text}{text }{text}}
\expanded{\myrowcont{text}{text}{text}{text }}

 \expanded{\myrow{\lipsum[12]}{text}{\lipsum[12]}{text}{text}{text)}{text}{text }{text}}
\expanded{\myrowcont{text}{text}{text}{text }}

\expanded{\myrow{text}{text}{text}{text}{text}{text)}{text}{text }{text}}
\expanded{\myrowcont{text}{text}{text}{text }}


\end{longtblr}  

\end{document}
```

And the result:
![text](https://user-images.githubusercontent.com/17953811/225959055-314727da-1542-4790-8d4c-411345c8f5b7.jpg)

**Comment by muzimuzhi** [comment] 2023-03-17 16:15
duplicate of #221

**Closed** 2023-03-17 23:30 UTC
Labels: duplicate
