### ISSUE TITLE
+matrix environment doesn't work in align environment

### ISSUE THREAD

**Issue by ddddavid-he** [lvjr/tabularray#225] opened 2022-04-02 08:49 UTC
When I tried to put +Bmatrix environment inside an align environment for better appearance like this
<img width="540" alt="截屏2022-04-02 16 47 47" src="https://user-images.githubusercontent.com/58453183/161375270-5ab43f9e-37af-4354-9a01-9ef7f6f62bb2.png">

I meet the problem
<img width="599" alt="截屏2022-04-02 16 48 33" src="https://user-images.githubusercontent.com/58453183/161375339-6b5b219b-d4ac-4ce6-a04f-a190fd0473a2.png">

I'm using the TexLive 2021 and all the packages are updated to the newest version.

**Comment by lvjr** [comment] 2022-04-02 10:27
It is a duplicate of issue #143.

PS: Please always post the source code instead of an image.

**Closed by lvjr** 2022-04-02 10:27 UTC
