### ISSUE TITLE
longtblr adds unnecessary page break with positive parskip

### ISSUE THREAD

**Issue by fefrei** [lvjr/tabularray#203] opened 2022-02-22 16:16 UTC
I'm having a problem where the `longtblr` environment occasionally appears to add unnecessary page breaks, like so:

![mwe](https://user-images.githubusercontent.com/3078885/155172655-b2ea9088-f6dc-4542-a81c-5c4d1d182bde.png)

The problem is somewhat fragile, and seems to depend on the vertical position when the `longtblr` is started. When it happens, two breaks are created, with a middle segment of the broken table *almost* fitting on the previous page.

It feels like `longtblr` is somehow confused about how much space is left on the page, decides where to break the table, but produces a first segment of the table that ends up not actually fitting (and inserting a page break after that segment, expecting that to be at the bottom of the page).

I have not been able to reproduce this without `parskip` (which might fit my guess above), but since reproducing the problem is somewhat fragile, that's no guarantee.

Here's the sources for the document shown in the screenshots above:
[mwe.zip](https://github.com/lvjr/tabularray/files/8118177/mwe.zip)

**Comment by lvjr** [comment] 2022-02-23 02:39
I would guess it is a duplicate of #200.

Please try the latest package file
https://github.com/lvjr/tabularray/raw/main/tabularray.sty

**Comment by fefrei** [comment] 2022-02-23 07:42
Thanks for your reply! Indeed, it looks quite similar to #200. However, the issue also reproduces with the latest `tabularray.sty` (included in the ZIP file above).

The example above is actually a minimal example, the document does nothing fancy at all:

```
\documentclass[11pt,twoside,a4paper]{article}

\usepackage[T1]{fontenc}
\usepackage{parskip}

\usepackage{tabularray}
\UseTblrLibrary{booktabs}

\NewTblrTheme{continued-only}{
  \SetTblrTemplate{head}{empty}
  \SetTblrTemplate{caption}{empty}
  \SetTblrTemplate{note}{empty}
  \SetTblrTemplate{remark}{empty}
}


\begin{document}

\raggedbottom

\section{Minimal Working Example}


\NewDocumentEnvironment{block}{}{
    \newcommand{\exampleline}{Lorem Ipsum & Dolor Sit & Amet \\}
    \subsection*{Subsection}
    \begin{longtblr}[entry=none, label=none, presep=0pt, headsep=0pt, postsep=0pt, theme=continued-only, expand=\exampleline]{colspec={X[leftsep=0pt, co=3]X[co=4]X[rightsep=0pt, co=2]}, rowsep=1pt, hline{Z}={\heavyrulewidth}, rowspec={Q[font=\bfseries, rowsep=2pt]Q[abovesep=2pt]}, rowhead=1}
        \toprule
        Lo & Do & Am \\\midrule
}{
    \end{longtblr}\par
}


\input{tables}


\end{document}
```

The `tables.tex` just contains blocks like this of varying length:

```
\begin{block}
	\exampleline
        % ...
	\exampleline
\end{block}
```

I've kept the full `tables.tex` because triggering this is so fragile – with the full list of example tables, it's quite likely to get a repro somewhere in the document if minor changes (e.g. to the page layout) cause the particular example screenshotted above to no longer repro the issue.

**Comment by lvjr** [comment] 2022-02-23 12:13
Your example is still too large. I managed to make a real minimal example from the example of issue #200:

```latex
\documentclass[12pt]{article}

\usepackage[a6paper,margin=15mm]{geometry}
\usepackage{tabularray}
\usepackage{parskip}

\begin{document}

\rule{4pt}{6cm}

\section{Section}

\begin{longtblr}[
  caption={Test},
  presep=0pt, postsep=0pt, headsep=0pt, footsep=0pt,
]{|X|X|X|X|}
   1 &  1  &  1  &  1 \\
   2 &  2  &  2  &  2 \\
   3 &  3  &  3  &  3 \\
   4 &  4  &  4  &  4 \\
   5 &  5  &  5  &  5 \\
   6 &  6  &  6  &  6 \\
   7 &  7  &  7  &  7 \\
   8 &  8  &  8  &  8 \\
   9 &  9  &  9  &  9 \\
  10 & 10  & 10  & 10 \\
  11 & 11  & 11  & 11 \\
  12 & 12  & 12  & 12 \\
  13 & 13  & 13  & 13 \\
  14 & 14  & 14  & 14 \\
  15 & 15  & 15  & 15 \\
  16 & 16  & 16  & 16 \\
  17 & 17  & 17  & 17 \\
  18 & 18  & 18  & 18 \\
  19 & 19  & 19  & 19 \\
  20 & 20  & 20  & 20 \\
  21 & 21  & 21  & 21 \\
  22 & 22  & 22  & 22 \\
  23 & 23  & 23  & 23 \\
  24 & 24  & 24  & 24 \\
  25 & 25  & 25  & 25 \\
  26 & 26  & 26  & 26 \\
  27 & 27  & 27  & 27 \\
  28 & 28  & 28  & 28 \\
  29 & 29  & 29  & 29 \\
  30 & 30  & 30  & 30 \\
\end{longtblr}

\end{document}
```

![image](https://user-images.githubusercontent.com/4239949/155317227-b339e996-9241-437c-bbc9-a4fc0c5847d4.png)

**Comment by lvjr** [comment] 2022-02-23 23:56
As a quick workaound, you may change `\subsection*{Subsection}` to `\textbf{Subsection}` in your code.

**Comment by fefrei** [comment] 2022-02-24 07:58
This does not work around the problem in general, it only changes vertical heights enough to not reproduce the issue in your example anymore. In my full example from the ZIP file, with your replacement, it now reproduces on page 1:

![image](https://user-images.githubusercontent.com/3078885/155481780-0d585bb3-c8ab-4fb1-a6f8-a170c2e07752.png)

A workaround that does seem to work in all cases is to set `parskip` to zero and manually insert `\vspace`s until things look good again.

**Comment by lvjr** [comment] 2022-02-24 13:20
@hconhegg Please post the 1em-parskip example here. Furthermore, can you reproduce the prolem with zero parskip?

**Comment by hconhegg** [comment] 2022-02-24 14:00
I have not seen this be a problem without parskip yet. I will try to prioritize this tomorrow.

**Comment by fefrei** [comment] 2022-02-24 16:11
Here's a very minimal example that merely manually sets `\parskip` to an (absurdly) non-zero value:

```latex
\documentclass[11pt,twoside,a4paper]{article}

\usepackage{tabularray}

\begin{document}

\setlength{\parskip}{8cm}

A

B

\begin{longtblr}{colspec={XXXX}, hlines, vlines}
   1 &  1  &  1  &  1 \\
   2 &  2  &  2  &  2 \\
   3 &  3  &  3  &  3 \\
   4 &  4  &  4  &  4 \\
   5 &  5  &  5  &  5 \\
   6 &  6  &  6  &  6 \\
   7 &  7  &  7  &  7 \\
   8 &  8  &  8  &  8 \\
   9 &  9  &  9  &  9 \\
  10 & 10  & 10  & 10 \\
\end{longtblr}

\end{document}
```

Here's how this renders for me:

![image](https://user-images.githubusercontent.com/3078885/155562134-3cc9ea2e-8ad1-45e1-bd98-8b5f1877b61d.png)

The large `\parskip` makes it clear that the `\parskip` is taken into account _somehow_ (the table on page 2 is clearly meant for the remainder of page 1 _minus the required `\parskip`_, otherwise, a lot more rows would fit), but it seems like it barely does not fit on page 1 in the end.

**Comment by lvjr** [comment] 2022-02-24 16:35
Good example! I think resetting `\parskip` to zero  at the beginning of `longtblr` environment would be enough to solve this problem.

**Comment by lvjr** [comment] 2022-05-07 08:03
This bug has been fixed.

**Closed by lvjr** 2022-05-07 08:03 UTC
Labels: bug
