### ISSUE TITLE
Multirow cell of longtblr exhibits strange page break

### ISSUE THREAD

**Issue by Kuido** [lvjr/tabularray#453] opened 2023-11-13 09:59 UTC
The longtblr 

![image](https://github.com/lvjr/tabularray/assets/7403372/650deb8e-b642-4ef6-8e94-f10e1c3de2da)

is broken as

![image](https://github.com/lvjr/tabularray/assets/7403372/2c270c01-5708-4641-bdc1-c939ec70b2f5)

```
Example LaTeX code:

\documentclass{article}
\usepackage{tabularray}

\begin{document}

\def\example{\begin{longtblr}[
    caption={Example}
]{
    hlines,
    colspec = {|Q[l]|Q[l]|},
    cell{1}{1} = {r=5,c=1}{},
}
  aaaaaa & bbbbbb \\
   & bbbbbb \\
   & bbbbbb \\
   & bbbbbb \\
   & bbbbbb \\
\end{longtblr}}

\example

\vspace*{.65\textheight}

\example

\end{document}
```

**Comment by muzimuzhi** [comment] 2023-11-13 11:08
Yes, this is a known limitation that page breaks are allowed in the middle of a vertical spanning cell, see #442.

I'm closing this as a duplicate of #442.

**Comment by muzimuzhi** [comment] 2023-11-13 11:10
Duplicate of #442

**Closed** 2023-11-13 11:10 UTC
