### ISSUE TITLE
Alignment issue with SIunitx

### ISSUE THREAD

**Issue by mhabets** [lvjr/tabularray#73] opened 2021-08-17 07:01 UTC
![image](https://user-images.githubusercontent.com/2016449/129677747-dd95408e-f933-45fd-9ef1-c0a933a99058.png)

The issue happens when using column long heading AND a multi column row.

```latex
\documentclass{article}
\usepackage{tabularray}
\UseTblrLibrary{siunitx}

\begin{document}
\begin{tblr}[
  caption = {Right alignment issue}
]{
 colspec={
   l
   X
   Q[si={table-format=3.0}, r]
   Q[si={table-format=8.0}, r]
   Q[si={table-format=3.0}, r]
   c
   Q[si={table-format=3.0}, r]
   Q[si={table-format=8.0}, r]
   Q[si={table-format=3.0}, r]
 },
 rowhead = 3,
}
& & {{{H}}} & {{{Long header}}} & {{{H}}} & & {{{H}}} & {{{Long header}}} & {{{H}}}\\
%\multicolumn{9}{l}{Row Heading} \\
\SetCell[c=9]{l} Row Heading \\
& Alpha & 0 & 10000000 & 95 &   & 0 & 0 & 95\\
& Beta & {{{-}}} & {{{-}}} & 10 &   & {{{-}}} & {{{-}}} & 10\\
& Gamma & {{{-}}} & 500000 & 11 &   & {{{-}}} & {{{-}}} & 11\\
& Epsilon & {{{-}}} & {{{-}}} & 8 &   & {{{-}}} & {{{-}}} & 8\\
\end{tblr}

\end{document}
```

**Comment by lvjr** [comment] 2021-08-17 07:14
See https://github.com/lvjr/tabularray/issues/40#issuecomment-884889628. You need to write
````latex
Q[si={table-format=3.0,table-number-alignment=right}, r]
````
The point is: use `table-number-alignment=right` for numeric values, and use `r` for non-numeric values.

**Comment by mhabets** [comment] 2021-08-17 07:25
Oops, sure. I missed that additional option. Sorry. It is a bit verbose but ok. Thank you 👍 

Note: it was confusing that it was working correctly without the multi column row.

**Comment by lvjr** [comment] 2021-08-17 07:33
> Note: it was confusing that it was working correctly without the multi column row.

It is a strange result. Later I will try to find the cause and decide whether it is a bug or not.

**Comment by lvjr** [comment] 2022-01-28 11:32
I will provide a minimal example and close this bug for now:

```latex
\documentclass{article}

\usepackage{tabularray}
\UseTblrLibrary{siunitx}

\begin{document}

\section{Without multicolumn row}

\begin{tblr}{hlines,vlines,colspec={llQ[si={table-format=8.0},r]}}
  &       & {{{Long header}}} \\
  & Alpha &     10000000      \\
  & Beta  &       500000      \\
\end{tblr}

\section{With multicolumn row}

\begin{tblr}{hlines,vlines,colspec={llQ[si={table-format=8.0},r]}}
\SetCell[c=3]{l} Row Heading  \\
  &       & {{{Long header}}} \\
  & Alpha &     10000000      \\
  & Beta  &       500000      \\
\end{tblr}

\end{document}
```
![image](https://user-images.githubusercontent.com/4239949/151539656-05cf633c-3241-4aad-8e04-2752e1ca0de4.png)

**Closed by lvjr** 2022-01-28 11:32 UTC
