### ISSUE TITLE
TeXLive 2023 complaining about undeclared prop variables in tabularray.sty

### ISSUE THREAD

**Issue by genovese** [lvjr/tabularray#475] opened 2024-02-15 22:45 UTC
I just upgraded from TeXLive2022 to TeXLive2023 and documents that had compiled now complained about undefined control sequences for tabularray's various prop-type variables which appear to be set before being declared:

```
\g__tblr_defined_hdash_styles_prop
\g__tblr_defined_vdash_styles_prop
\g__tblr_initial_table_prop       
\g__tblr_initial_rows_prop        
\g__tblr_initial_columns_prop     
\g__tblr_initial_cells_prop       
\g__tblr_initial_hlines_prop      
\g__tblr_initial_vlines_prop      
```
The only way I can now get it to compile is to insert the following shim before loading the package. This seems to work without problem, but I made an assumption about the flat format of the property lists:

```
\ExplSyntaxOn
  \prop_new:N \g__tblr_defined_hdash_styles_prop
  \prop_new:N \g__tblr_defined_vdash_styles_prop
  \prop_new:N \g__tblr_initial_table_prop       
  \prop_new:N \g__tblr_initial_rows_prop        
  \prop_new:N \g__tblr_initial_columns_prop     
  \prop_new:N \g__tblr_initial_cells_prop       
  \prop_new:N \g__tblr_initial_hlines_prop      
  \prop_new:N \g__tblr_initial_vlines_prop      
\ExplSyntaxOff
```

I'm guessing that the newer tex version is enforcing pre-declaration for these whereas the old one did not. But it seems odd that no one else has reported this.

Here's a minimal example that failed (and again it worked fine for TeXLive2022 just minutes earlier):

```
\documentclass[12pt]{article}

% Uncommenting this shim fixes the problem
%\ExplSyntaxOn
%  \prop_new:N \g__tblr_defined_hdash_styles_prop
%  \prop_new:N \g__tblr_defined_vdash_styles_prop
%  \prop_new:N \g__tblr_initial_table_prop       
%  \prop_new:N \g__tblr_initial_rows_prop        
%  \prop_new:N \g__tblr_initial_columns_prop     
%  \prop_new:N \g__tblr_initial_cells_prop       
%  \prop_new:N \g__tblr_initial_hlines_prop      
%  \prop_new:N \g__tblr_initial_vlines_prop      
%\ExplSyntaxOff

\usepackage{tabularray}

\begin{document}

\begin{center}
  \begin{tblr}{cc}
    \textbf{Input} & \textbf{Output} \\
    \hline
    1 & \texttt{hello}\\
    10 & \texttt{world}\\
    100 & \texttt{!}
  \end{tblr}
\end{center}

\end{document}
```

I wanted to alert you to this problem. Also, please let me know if there is a better solution than what I used; if not, I'll insert it into my local copy of the package.

Thanks for a great package!  I really appreciate it.

**Comment by davidcarlisle** [comment] 2024-02-15 22:57
duplicate of #474 (already fixed in the sources)

**Closed** 2024-02-17 06:01 UTC
Labels: duplicate
